### ISSUE TITLE
Building and managing dependencies in local development

### ISSUE THREAD

**Issue by mtodd** [tenderlove/our_pc#5]
I don't have the necessary dependencies installed on my system and they're not explicitly declared with tooling to help get things set up for new contributors.

My preference would be a `Brewfile` to declare the dependencies for MacOS environment and maybe a `script/bootstrap` to get things setup so that `rake test` works.

**Comment by aonemd** [comment]
@mtodd All the dependencies are installed via the rake task, `:deps`. You only need to have the [protocol buffer compiler](https://github.com/protocolbuffers/protobuf/releases) setup in your system's `$PATH`. Maybe this should be added to the README?

**Comment by mtodd** [comment]
My mistake, I was running `rake -T` rather than `rake -P` (and didn't look at the source).

I have `protoc` in my `PATH`:
```
our_pc:master $ which protoc 
/usr/local/bin/protoc
our_pc:master $ protoc --version 
libprotoc 3.6.1
```

but when I run `rake deps`, the `ds9` gem appears to fail to build because of missing `nghttp2` headers.

👍 to documenting build instructions in the README.

**Comment by BobbyMcWho** [comment]
@mtodd I don't seem to be able to reproduce the nghttp2 issue, and by default the deps function will be called anytime you run `rake server`, `rake client`, or just `rake` so it should install those for you if it can't import them. 

Edit: `rake test` was the only task not running `deps` first

**Comment by mtodd** [comment]
@BobbyMcWho the issue was that I didn't have `nghttp2` installed with homebrew. Without it installed, `deps` will just fail to install `ds9`. Ideally, a `Brewfile` would  make the `nghttp2` dependency explicit rather than implicit via the `ds9` gem.

Once I installed `nghttp2` with homebrew, `rake deps` works and I can get the tests to run.

**Comment by tenderlove** [comment]
We should probably add a Gemfile too, I was just lazy 😅
